import type { TranslationKey } from './index';

/** Simplified Chinese translations. */
export const ZH_CN: Record<TranslationKey, string> = {
    statusPlayed: '已完成',
    statusPlaying: '游玩中',
    statusDropped: '已弃置',
    statusSandbox: '沙盒',
    statusWishlist: '愿望单',
    statusNotStarted: '未开始',
    statusFavorite: '收藏',
    statusPlanned: '计划中',
    statusWatching: '观看中',
    statusCompleted: '已完成',
    statusReadCompleted: '已读完',
    statusPaused: '已暂停',
    statusPlanToRead: '计划阅读',
    statusReading: '阅读中',

    search: '搜索',
    searchPlaceholder: '搜索…',
    sort: '排序',
    sortName: '名称',
    sortSeries: '系列',
    sortRating: '评分',
    sortYear: '年份',
    sortDateCompleted: '完成日期',
    sortDateWatched: '观看日期',
    sortDateRead: '读完日期',
    sortOrder: '顺序',
    sortAsc: '升序',
    sortDesc: '降序',
    status: '状态',
    filter: '筛选',
    filterAdult: '成人内容（18+）',
    filterFlags: '标记',
    tags: '标签',
    genres: '类型',
    plans: '计划',
    tagsEmpty: '暂无标签',
    view: '视图',
    random: '随机游戏',
    randomAnime: '随机动漫',
    randomBook: '随机书籍',
    randomManga: '随机漫画',
    stats: '统计',
    settings: '设置',

    viewGrid: '竖版',
    viewHorizontal: '横版',
    modeCustom: '自定义封面',

    settingsColumns: '列数',
    settingsCardSize: '卡片尺寸',
    settingsCardStyle: '卡片样式',
    settingsCardStyleDesc: '仅适用于动漫、剧集、书籍和漫画',
    settingsCardStyleHover: '悬停预览',
    settingsCardStyleProgress: '底部进度栏',
    settingsCustomCardSize: '自定义卡片尺寸',
    settingsCustomCardSizeDesc: '使用自定义宽度、高度和比例，不采用预设卡片尺寸',
    settingsCardMinWidth: '卡片目标宽度',
    settingsCardMinHeight: '卡片最小高度',
    settingsCardImageRatio: '海报比例（宽/高）',
    settingsHorizontalCardMinWidth: '横版目标宽度',
    settingsHorizontalCardHeight: '横版卡片高度',
    settingsCardMinWidthDesc: '空间足够时，每列中的卡片会保持此宽度',
    settingsCardMinHeightDesc: '竖版卡片海报区域的最小高度',
    settingsCardImageRatioDesc: '0.67 = 经典 2:3 海报，1.0 = 正方形',
    settingsHorizontalCardMinWidthDesc: '横版卡片的最小宽度',
    settingsHorizontalCardHeightDesc: '横版卡片的固定高度',
    settingsCustomCardReset: '重置自定义卡片参数',
    settingsAnimeSeasonProgress: '在动漫卡片上显示季度进度',
    settingsAnimeEpisodeProgress: '在动漫卡片上显示集数进度',
    settingsSeasonProgress: '在卡片上显示季度进度',
    settingsEpisodeProgress: '在卡片上显示集数进度',
    settingsPageProgress: '在卡片上显示页数进度',
    settingsChapterProgress: '在卡片上显示章节进度',
    settingsVolumeProgress: '在卡片上显示卷数进度',
    settingsSizeSmall: '小',
    settingsSizeMedium: '中',
    settingsSizeLarge: '大',
    settingsOrientation: '卡片方向',
    settingsOrientationVertical: '竖版',
    settingsOrientationHorizontal: '横版',
    settingsColor: '强调色',
    settingsShowAddModeChoice: '显示添加方式选择',
    settingsShowAddModeChoiceDesc: '点击加号时选择“数据源搜索”或“手动创建”。关闭后将直接打开数据源搜索。',
    settingsLanguage: '语言',
    settingsReset: '重置设置',
    settingsCardClick: '点击卡片',
    settingsCardClickDesc: '选择在资料库中单击卡片时执行的操作。',
    settingsCardClickOpenNote: '打开笔记',
    settingsCardClickEditItem: '编辑条目',
    settingsMediaGames: '显示游戏',
    settingsMediaAnime: '显示动漫',
    settingsMediaMovies: '显示电影',
    settingsMediaSeries: '显示剧集',
    settingsMediaBooks: '显示书籍',
    settingsMediaManga: '显示漫画',
    settingsParticle: '粒子效果',
    settingsParticleNone: '无',
    settingsParticleSakura: '🌸 樱花',
    settingsParticleSnow: '❄️ 飘雪',
    settingsParticleIntensity: '粒子数量',
    settingsFolder: '文件夹路径',
    settingsGames: '游戏',
    settingsAnime: '动漫',
    settingsMovies: '电影',
    settingsSeries: '剧集',
    settingsBooks: '书籍',
    settingsManga: '漫画',
    settingsMedia: '媒体',
    settingsMediaDesc: '在一个位置配置各类资料库。',
    settingsMediaTabs: '媒体类型设置',
    settingsIntegrationTemplateTabs: '媒体类型模板',
    settingsExperiment: '实验功能',
    settingsTitle: 'LOREBASE 设置',
    settingsLayoutMode: '设置布局',
    settingsLayoutTabs: '分区标签页',
    settingsLayoutAccordion: '可折叠分区',
    settingsSupportTitle: '支持 LOREBASE',
    settingsSupportDesc: 'Discord、Ko-fi 和 Patreon。',
    settingsSectionGeneralDesc: '语言、效果和强调色。',
    settingsSectionCustomizationDesc: '卡片预览、徽章、状态和计划。',
    settingsSectionMediaDesc: '各媒体类型的资料库设置。',
    settingsSectionIntegrationsDesc: '数据源和笔记模板。',
    settingsSectionSyncDesc: '导入并同步外部资料库。',
    settingsSectionExperimentDesc: '实验功能和本地图片。',
    settingsSectionDangerDesc: '重置全部 LOREBASE 设置。',
    settingsSectionAboutDesc: '版本与插件信息。',
    settingsAbout: '关于',
    settingsAboutDesc: 'LOREBASE 是一个媒体资料库，可管理游戏、动漫、电影、剧集、书籍和漫画，并提供自定义卡片、进度、评分和元数据集成。',
    settingsAboutVersion: '版本',
    settingsAboutAuthor: '作者',
    settingsAboutObsidian: 'Obsidian',
    settingsAboutPlatforms: '平台',
    settingsAboutDesktop: '桌面端',
    settingsAboutDesktopMobile: '桌面端和移动端',
    settingsAboutLinks: '链接',
    settingsAboutGitHub: 'GitHub 仓库',
    settingsAboutChangelog: '更新日志 / 版本说明',
    settingsAboutDocumentation: '文档',
    settingsAboutAttribution: '数据来源与归属',
    settingsAboutAttributionDesc: 'LOREBASE 可以连接第三方元数据服务。所有商标、数据和图片均归各自所有者所有。',
    settingsAboutAttributionTmdbNotice: '本产品使用 TMDB API，但未经 TMDB 认可或认证。',
    settingsSupportUnavailable: '尚未配置链接',
    settingsDangerZone: '危险区域',
    settingsDangerZoneWarning: '此区域中的操作会影响全部 LOREBASE 设置，且无法撤销。',
    settingsResetAllButton: '重置全部设置',
    settingsGeneral: '通用',
    settingsShowAdult: '显示成人内容（18+）',
    settingsBadges: '卡片自定义',
    settingsPreviewMode: '预览类型',
    settingsPreviewGame: '游戏',
    settingsPreviewAnime: '动漫',
    settingsPreviewMovie: '电影',
    settingsPreviewSeries: '剧集',
    settingsPreviewBook: '书籍',
    settingsPreviewManga: '漫画',
    settingsDescriptionLines: '简介行数',
    settingsDescriptionLinesDesc: '默认为 4 行。拖动滑块可增加行数。',
    settingsBookCoverEffect: '精装书封面效果',
    settingsBookCoverEffectDesc: '为书籍类卡片添加书脊、内嵌封面阴影和轻微悬浮效果。',
    settingsBadgesStatus: '状态徽章',
    settingsBadgesRating: '评分徽章',
    settingsBadgesFavorite: '收藏徽章',
    settingsBadgesStatusPosition: '状态位置',
    settingsBadgesRatingPosition: '评分位置',
    settingsBadgesFavoritePosition: '收藏位置',
    settingsBadgesStatusIconOnly: '状态仅显示图标',
    settingsBadgesFavoritePulse: '收藏轻微脉动效果',
    settingsBadgesRatingMode: '评分样式',
    settingsBadgesRatingModeStar: '星级',
    settingsBadgesRatingModeEmoji: '表情',
    settingsCompletionDateBadgeFormat: '完成日期格式',
    settingsCompletionDateBadgeFormatShort: '状态 · 7月22日',
    settingsCompletionDateBadgeFormatFull: '状态 · 2025年7月22日',
    settingsBadgesEditorHint: '单击徽章可启用或关闭；将徽章拖到四个角落区域之一。',
    settingsOverlayHint: '将鼠标悬停在卡片上，可拖动标题、年份、格式和简介。拖动简介右下角可调整行数；双击字段可启用或关闭。',
    settingsOverlayReadoutIdle: '请在悬停卡片中选择标题、年份、格式或简介。',
    settingsOverlayApplyAllMedia: '将悬浮层更改应用到所有媒体',
    settingsOverlayApplyAllMediaDesc: '启用后，预览文字和徽章更改将在所有媒体类型之间同步。',
    settingsBadgesPosition: '徽章位置',
    settingsBadgesPosTopLeft: '左上',
    settingsBadgesPosTopRight: '右上',
    settingsBadgesPosBottomLeft: '左下',
    settingsBadgesPosBottomRight: '右下',
    settingsDescLanguage: '界面语言',
    settingsDescColor: '主题强调色',
    settingsDescFolder: '输入资料库中的任意文件夹路径。已有文件夹会显示为建议；新建嵌套路径会在首次写入时创建。',
    settingsDescColumns: '网格最大列数（3–8）。窗格较窄时会自动减少列数。',
    settingsDescOrientation: '选择卡片布局和图片宽高比',
    settingsDescShowAdult: '在“全部”视图中显示成人内容',
    settingsDescReset: '将全部设置恢复为默认值',
    settingsIntegrations: '集成',
    settingsIntegrationsEnable: '启用集成',
    settingsIntegrationsEnableDesc: '启用元数据源和模板',
    settingsIntegrationsRequestCooldown: '请求间隔',
    settingsIntegrationsRequestCooldownDesc: '在所选条目之间额外等待的秒数。数据源的安全限速始终有效（设为 0 只会关闭这段额外等待）。',
    settingsIntegrationsDiagnostics: '请求诊断',
    settingsIntegrationsDiagnosticsDesc: '检查最近的数据源请求、失败、重试和当前限速。',
    settingsIntegrationsDiagnosticsSessionOnly: '最近 2,000 条请求和导入事件仅保留在当前 Obsidian 会话中。Steam 同步会记录游戏名称和 App ID，以便识别失败条目；不会记录搜索词、查询参数、请求正文、请求头、API 密钥或令牌。',
    settingsIntegrationsDiagnosticsProviderFilter: '数据源',
    settingsIntegrationsDiagnosticsAllProviders: '全部数据源',
    settingsIntegrationsDiagnosticsErrorsOnly: '仅错误',
    settingsIntegrationsDiagnosticsActiveCooldowns: '当前限速',
    settingsIntegrationsDiagnosticsNoCooldowns: '当前没有暂停的数据源。',
    settingsIntegrationsDiagnosticsRecentRequests: '最近的请求和导入',
    settingsIntegrationsDiagnosticsEmpty: '暂无匹配的请求事件。',
    settingsIntegrationsDiagnosticsRefresh: '刷新',
    settingsIntegrationsDiagnosticsCopy: '复制报告',
    settingsIntegrationsDiagnosticsClear: '清空日志',
    settingsIntegrationsDiagnosticsCopied: '诊断报告已复制。',
    settingsIntegrationsDiagnosticsCleared: '诊断日志已清空。',
    settingsIntegrationsDiagnosticsSuccess: '成功',
    settingsIntegrationsDiagnosticsError: '错误',
    settingsIntegrationsDiagnosticsBlocked: '已阻止',
    settingsIntegrationsDiagnosticsRetry: '重试',
    settingsIntegrationsDiagnosticsCreated: '已创建',
    settingsIntegrationsDiagnosticsUpdated: '已更新',
    settingsIntegrationsDiagnosticsSkipped: '已跳过',
    settingsIntegrationsDiagnosticsCancelled: '已取消',

    settingsIntegrationsSteamSyncDesc: '导入 Steam 资料库并保持游戏数据同步。',
    settingsIntegrationsProviders: '数据源',
    settingsIntegrationsMediaProviders: '媒体数据源',
    settingsIntegrationsTemplates: '模板',
    settingsIntegrationsProviderRawg: 'RAWG（游戏）',
    settingsIntegrationsProviderSteam: 'Steam（游戏）',
    settingsIntegrationsProviderIgdb: 'IGDB（游戏）',
    settingsIntegrationsProviderAnilist: 'AniList（动漫）',
    settingsIntegrationsProviderJikan: 'Jikan / MyAnimeList（动漫）',
    settingsIntegrationsProviderShikimori: 'Shikimori（动漫）',
    settingsIntegrationsProviderTmdb: 'TMDB（电影和剧集）',
    settingsIntegrationsProviderTvmaze: 'TVmaze（剧集）',
    settingsIntegrationsProviderOmdb: 'OMDb（电影和剧集）',
    settingsIntegrationsProviderHardcover: 'Hardcover（书籍）',
    settingsIntegrationsProviderGooglebooks: 'Google Books（书籍）',
    settingsIntegrationsProviderMangaupdates: 'MangaUpdates（漫画）',
    settingsIntegrationsProviderMangadex: 'MangaDex（漫画）',
    settingsIntegrationsProviderKeyRequired: '需要 API 密钥',
    settingsIntegrationsProviderKeyOptional: '不需要 API 密钥',
    settingsIntegrationsProviderKeyPlaceholder: 'API 密钥',
    settingsIntegrationsProviderClientIdPlaceholder: '客户端 ID',
    settingsIntegrationsProviderClientSecretPlaceholder: '客户端密钥',
    settingsIntegrationsProviderIgdbHelpTitle: '如何获取 IGDB 凭据',
    settingsIntegrationsProviderIgdbHelpText: '在 Twitch 开发者控制台创建应用，然后复制客户端 ID 并生成客户端密钥。IGDB 使用这些 Twitch 凭据访问 API。',
    settingsIntegrationsProviderIgdbTwitchLink: '打开 Twitch 开发者控制台',
    settingsIntegrationsProviderIgdbDocsLink: '打开 IGDB API 文档',
    settingsIntegrationsProviderRawgHelpTitle: '如何获取 RAWG API 密钥',
    settingsIntegrationsProviderRawgHelpText: '注册或登录 RAWG，打开 API 文档，然后复制 API 密钥。',
    settingsIntegrationsProviderRawgLink: '打开 RAWG API 文档',
    settingsIntegrationsProviderTmdbHelpTitle: '如何获取 TMDB API 密钥',
    settingsIntegrationsProviderTmdbHelpText: '注册或登录 TMDB，打开 API 设置，然后复制 v3 API 密钥。',
    settingsIntegrationsProviderTmdbLink: '打开 TMDB API 文档',
    settingsIntegrationsProviderTvmazeHelpTitle: 'TVmaze API',
    settingsIntegrationsProviderTvmazeHelpText: 'TVmaze 搜索无需 API 密钥。此字段为可选项，预留供未来使用。',
    settingsIntegrationsProviderTvmazeLink: '打开 TVmaze API 文档',
    settingsIntegrationsProviderOmdbHelpTitle: '如何获取 OMDb 密钥',
    settingsIntegrationsProviderOmdbHelpText: '在 OMDb 申请 API 密钥并粘贴到此处。',
    settingsIntegrationsProviderOmdbLink: '打开 OMDb API 密钥页面',
    settingsIntegrationsProviderHardcoverHelpTitle: 'Hardcover API 密钥',
    settingsIntegrationsProviderHardcoverHelpText: 'Hardcover 是主要书籍数据源。请在 Hardcover 账户中创建 API 令牌并粘贴到此处。',
    settingsIntegrationsProviderHardcoverLink: '打开 Hardcover API 设置',
    settingsIntegrationsProviderGooglebooksHelpTitle: 'Google Books API 密钥',
    settingsIntegrationsProviderGooglebooksHelpText: 'Google Books 的公开请求经常受到限速。添加 API 密钥可提高此数据源的可靠性。',
    settingsIntegrationsProviderGooglebooksLink: '打开 Google Books API 文档',
    settingsIntegrationsProviderTest: '测试',
    settingsIntegrationsImageStorage: '本地图片',
    settingsIntegrationsImageStorageDesc: '实验功能：将数据源图片保存到资料库',
    settingsIntegrationsImageStorageEnable: '将导入图片保存到本地',
    settingsIntegrationsImageStorageEnableDesc: '下载海报和图片字段，并在新笔记中写入资料库本地路径',
    settingsIntegrationsImageStorageFolder: '图片文件夹',
    settingsIntegrationsImageStorageFolderDesc: '用于保存游戏和动漫下载图片的资料库文件夹',
    settingsIntegrationsImageStorageDownloadExisting: '下载现有图片',
    settingsIntegrationsImageStorageDownloadExistingDesc: '扫描现有游戏和动漫笔记，将远程图片保存到本地并更新属性',
    settingsIntegrationsImageStorageDownloadStarted: '正在下载现有 LOREBASE 图片…',
    settingsIntegrationsImageStorageDownloadDone: '现有图片下载完成',
    settingsIntegrationsGamesProvider: '游戏数据源',
    settingsIntegrationsAnimeProvider: '动漫数据源',
    settingsMoviesSeries: '电影和剧集',
    settingsIntegrationsGamesProviderDesc: '选择游戏数据源',
    settingsIntegrationsAnimeProviderDesc: '选择动漫数据源',
    settingsIntegrationsGamesTemplate: '游戏模板',
    settingsIntegrationsAnimeTemplate: '动漫模板',
    settingsIntegrationsMoviesTemplate: '电影模板',
    settingsIntegrationsSeriesTemplate: '剧集模板',
    settingsIntegrationsBooksTemplate: '书籍模板',
    settingsIntegrationsMangaTemplate: '漫画模板',
    settingsIntegrationsTemplateContent: '模板内容',
    settingsIntegrationsTemplateMode: '模板模式',
    settingsIntegrationsTemplateModeDesc: '选择简单或高级模板编辑器',
    settingsIntegrationsTemplateModeSimple: '简单',
    settingsIntegrationsTemplateModeAdvanced: '高级',
    settingsIntegrationsTemplateFields: '包含的字段',
    settingsIntegrationsHowLongToBeat: 'HowLongToBeat',
    settingsIntegrationsHowLongToBeatDesc: '从 HowLongToBeat 填充主线、主线+支线和完美通关时长',
    settingsIntegrationsSteamGridDb: 'SteamGridDB 封面',
    settingsIntegrationsSteamGridDbDesc: '找不到合适封面时，使用 SteamGridDB 提供的 600×900 竖版 Steam 封面',
    settingsIntegrationsSteamGridDbApiKey: 'SteamGridDB API 密钥',
    settingsIntegrationsSteamGridDbHelpTitle: '如何获取 SteamGridDB API 密钥',
    settingsIntegrationsSteamGridDbHelpText: '注册或登录 SteamGridDB，打开偏好设置，然后复制 API 密钥。',
    settingsIntegrationsSteamGridDbLink: '打开 SteamGridDB 偏好设置',

    templateFieldType: '类型',
    templateFieldName: '名称',
    templateFieldImage: '图片',
    templateFieldImageHorizontal: '横版图片',
    templateFieldPoster: '海报',
    templateFieldPosterHorizontal: '横版海报',
    templateFieldPlot: '简介',
    templateFieldScoreImdb: 'IMDb 评分',
    templateFieldCommunityRating: '社区评分',
    templateFieldCommunityVotes: '社区评分人数',
    templateFieldCommunityRatingProvider: '评分来源',
    templateFieldTags: '标签',
    templateFieldYear: '年份',
    templateFieldStudios: '制作公司',
    templateFieldFormat: '格式',
    templateFieldRating: '个人评分',
    templateFieldStatus: '状态',
    templateFieldDropped: '已弃置',
    templateFieldFavorite: '收藏',
    templateFieldUrl: '来源网址',
    templateFieldGameSeries: '游戏系列',
    templateFieldGenres: '类型',
    templateFieldPlatforms: '平台',
    templateFieldReleased: '发行日期',
    templateFieldRuntime: '时长',
    templateFieldDirector: '导演',
    templateFieldActors: '演员',
    templateFieldMovieParts: '电影分部',
    templateFieldSeriesParts: '剧集季度',
    templateFieldSeasons: '季度',
    templateFieldEpisodeCurrent: '当前集数',
    templateFieldEpisodeTotal: '总集数',
    templateFieldDevelopers: '开发商',
    templateFieldPublishers: '发行商',
    templateFieldMetacritic: 'Metacritic',
    templateFieldMain: '主线',
    templateFieldMainPlusSides: '主线 + 支线',
    templateFieldCompletionist: '完美通关',
    templateFieldAnimeParts: '动漫分部',
    templateFieldIntegrationSource: '集成来源',
    templateFieldAuthors: '作者',
    templateFieldPublisher: '出版社',
    templateFieldArtists: '画师',
    templateFieldPageCurrent: '当前页数',
    templateFieldPageTotal: '总页数',
    templateFieldChapterCurrent: '当前章节',
    templateFieldChapterTotal: '总章节',
    templateFieldVolumeCurrent: '当前卷数',
    templateFieldVolumeTotal: '总卷数',
    templateFieldMangaParts: '漫画分卷',
    editProgressMain: '主线',
    editProgressMainPlusSides: '主线 + 支线',
    editProgressPerfectionist: '完美通关',
    templateFieldUserRating: '用户评分',
    templateFieldPlayed: '已游玩',
    templateFieldPlaying: '游玩中',

    resetTitle: '恢复默认设置',
    resetSubtitle: '这会将插件的全部设置恢复为默认值。',
    resetWarning: '此操作无法撤销。',
    resetConfirm: '恢复默认值',
    resetConfirmAck: '我明白此操作无法撤销',

    statsTitle: '收藏统计',
    statsTotal: '总计',
    statsCompleted: '已完成',
    statsAvgRating: '平均评分',
    statsOf: '/',
    statsDistribution: '状态分布',
    statsRatingDistribution: '评分分布',
    statsAdditionalInfo: '其他信息',
    statsSeries: '系列',
    statsCustomPosters: '自定义海报',
    statsAdultContent: '成人内容（18+）',
    statsRated: '已评分',
    statsCompletionPercent: '完成度',

    ratingAwesome: '极佳',
    ratingGood: '不错',
    ratingOkay: '一般',
    ratingWeak: '较差',
    ratingBad: '很差',

    year: '年份',
    yearNotSpecified: '年份未知',
    noDescription: '暂无简介',
    noSeries: '无系列',
    noDate: '无日期',
    viewNew: '新视图',
    randomGame: '随机游戏',
    noGamesFound: '未找到游戏',
    noAnimeFound: '未找到动漫',
    noMoviesFound: '未找到电影',
    noSeriesFound: '未找到剧集',
    noBooksFound: '未找到书籍',
    noMangaFound: '未找到漫画',

    contextChangeStatus: '更改状态',
    contextChangeRating: '更改评分',
    contextAddFavorite: '加入收藏',
    contextRemoveFavorite: '取消收藏',
    contextEpisodePlusOne: '集数 +1',
    contextPagePlusOne: '页数 +1',
    contextChapterPlusOne: '章节 +1',
    contextEdit: '编辑',
    contextSourceLink: '关联数据源并自动填充',
    contextSourceRefresh: '从数据源更新',
    contextSourceChange: '更换数据源',
    contextDelete: '删除',
    contextClear: '清除',
    contextGames: '游戏',
    contextAnime: '动漫',

    editRating: '评分',
    editStatus: '状态',
    editFavorite: '收藏',
    editYear: '发行年份',
    editDescription: '简介',
    editDescriptionPlaceholder: '添加简短简介…',
    editMyNotesPlaceholder: '写下你的笔记…',
    editSeries: '系列',
    editNoSeries: '无系列',
    editAdult: '成人内容（18+）',
    editCustomPoster: '自定义海报',
    editSave: '保存',
    editCancel: '取消',
    editProgress: '进度',
    editGeneral: '基本信息',
    editCollection: '收藏信息',
    editPersonal: '个人记录',
    editMore: '更多',
    editCompletedOn: '完成日期',
    editDetails: '详细信息',
    editAdvanced: '高级',
    editClear: '清除',
    editSeasonCurrent: '当前季度',
    editSeasonTotal: '总季度数',
    editEpisodeCurrent: '当前集数',
    editEpisodeTotal: '总集数',
    editEpisodes: '集数',
    editPageCurrent: '当前页数',
    editPageTotal: '总页数',
    editChapterCurrent: '当前章节',
    editChapterTotal: '总章节',
    editVolumeCurrent: '当前卷数',
    editVolumeTotal: '总卷数',
    editFormat: '格式',
    editSummary: '简介',
    editUrl: '来源网址',
    editEpisodeInc: '增加 1 集',
    editPageInc: '增加 1 页',
    editChapterInc: '增加 1 章',
    editEnabled: '已启用',
    editDisabled: '已关闭',
    editPoster: '海报',
    editQuickSettings: '快速设置',
    editWishlistStatusLock: '启用后不能选择常规状态',
    editWishlistStatusLocked: '愿望单已启用。请先在快速设置中关闭愿望单，再选择状态。',
    editAdultVisibilityHint: '请在 Lorebase 设置中启用成人内容显示，才能在资料库中看到此条目',
    mediaSwitcher: '媒体',
    mediaSwitcherClose: '关闭媒体切换器',
    editSource: '元数据来源',
    editSourceConnected: '已关联',
    editSourceNotConnected: '未关联',
    editSourceLink: '关联并自动填充',
    editSourceRefresh: '更新数据',
    editSourceChange: '更换数据源',
    editTracking: '进度跟踪',
    editPersonalRating: '个人评分',
    editRatingHint: '点击星星进行评分',
    editSaved: '已保存',
    editUnsavedChanges: '有未保存的更改',
    editCharsShort: '字',
    editReleaseDate: '发行日期',
    editPublisher: '发行商 / 出版社',
    editDeveloper: '开发商',
    editPlatformPlaceholder: '添加平台…',
    editAddPlatform: '添加平台',
    editNoPlatforms: '未指定平台',
    editLocalPath: '本地路径',
    editOpen: '打开',
    editTagPlaceholder: '添加标签…',
    editStarted: '开始日期',
    editFinished: '完成日期',
    editToday: '今天',
    editMyNotes: '我的笔记',
    editDlc: 'DLC',
    editRefreshDlc: '刷新 DLC',
    editNoDlc: '无 DLC',
    editCollapseDlc: '收起 DLC',
    editDates: '日期',
    editAdded: '添加时间',
    editUpdated: '更新时间',
    editUnknown: '未知',
    editOverflow: '更多',
    editRemoveHint: '点击移除',
    editBreadcrumbGames: '编辑 / 游戏',
    editBreadcrumbAnime: '编辑 / 动漫',
    editBreadcrumbBooks: '编辑 / 书籍',
    editBreadcrumbManga: '编辑 / 漫画',
    editMovieTitle: '编辑电影',
    editSeriesTitle: '编辑剧集',
    editBookTitle: '编辑书籍',
    editMangaTitle: '编辑漫画',
    editAnimeParts: '作品分部',
    editAddPart: '+ 添加分部',
    editRemovePart: '移除分部',
    editCannotRemoveLastPart: '至少需要保留一个分部',
    editRelatedMedia: '关联媒体',
    editAddRelated: '+ 添加关联',
    editRelatedEmpty: '暂无关联媒体',
    editRelatedPickerTitle: '添加关联媒体',
    editTotalEpisodes: '总集数',
    editTotalPages: '总页数',
    editTotalChapters: '总章节',
    editActivePart: '当前分部',
    editActiveVolume: '当前卷',

    animePartsCheck: '检查分部',
    animePartsProviderTitle: '数据源作品分部',
    animePartsNew: '新增',
    animePartsSelected: '已选择',
    animePartsNoNew: '没有新分部',
    animePartsSourceMissing: '无法确定动漫数据源。',
    animePartsApply: '应用分部',
    planCheckLater: '稍后查看',
    planPlaySoon: '近期游玩',
    planWaitEarlyAccess: '等待抢先体验结束',
    planNextInQueue: '队列下一项',
    settingsStatusPlans: '状态与计划',
    settingsStatusPlansDesc: '重命名显示的状态标签并管理游戏快捷计划标签。',
    settingsGameStatusLabels: '游戏状态标签',
    settingsAnimeStatusLabels: '动漫状态标签',
    settingsMovieStatusLabels: '电影状态标签',
    settingsSeriesStatusLabels: '剧集状态标签',
    settingsBookStatusLabels: '书籍状态标签',
    settingsMangaStatusLabels: '漫画状态标签',
    settingsGamePlanTags: '游戏计划标签',
    settingsGamePlanTagsDesc: '这些值会保存为普通标签。',
    settingsStatusReset: '恢复默认标签',
    settingsPlanAdd: '添加计划',
    settingsPlanRemove: '移除计划',
    settingsPlanPlaceholder: '计划名称',
    settingsPlanNew: '新计划',
    settingsStatusMediaTabs: '状态标签对应的媒体类型',
    formatTv: 'TV',
    formatMovie: '电影',
    formatOva: 'OVA',
    formatOna: 'ONA',
    formatSpecial: '特别篇',

    deleteTitle: '删除游戏？',
    deleteSubtitle: '你即将永久删除此游戏。',
    deleteWarning: '此操作无法撤销。',
    deleteConfirmAck: '我明白此操作会永久删除该游戏',
    deleteConfirm: '删除',
    deleteCancel: '取消',
    deleteTitleAnime: '删除动漫？',
    deleteSubtitleAnime: '你即将永久删除此动漫。',
    deleteConfirmAckAnime: '我明白此操作会永久删除该动漫',
    deleteTitleMovie: '删除电影？',
    deleteSubtitleMovie: '你即将永久删除此电影。',
    deleteConfirmAckMovie: '我明白此操作会永久删除该电影',
    deleteTitleSeries: '删除剧集？',
    deleteSubtitleSeries: '你即将永久删除此剧集。',
    deleteConfirmAckSeries: '我明白此操作会永久删除该剧集',
    deleteTitleReading: '删除阅读条目？',
    deleteSubtitleReading: '你即将永久删除此阅读条目。',
    deleteConfirmAckReading: '我明白此阅读条目会被永久删除',

    notifyLoading: '正在加载…',
    commandOpenLibrary: '打开资料库',
    commandOpenGamesLibrary: '打开游戏库',
    commandOpenAnimeLibrary: '打开动漫库',
    commandOpenMoviesLibrary: '打开电影库',
    commandOpenSeriesLibrary: '打开剧集库',
    commandOpenBooksLibrary: '打开书库',
    commandOpenMangaLibrary: '打开漫画库',
    commandAddGame: '添加游戏',
    commandAddAnime: '添加动漫',
    commandAddMovie: '添加电影',
    commandAddSeries: '添加剧集',
    commandAddBook: '添加书籍',
    commandAddManga: '添加漫画',
    commandSteamSync: 'Steam 同步',
    commandImportNotes: '将笔记导入 LOREBASE',
    ribbonLibrary: 'LOREBASE 资料库',
    errorInitView: '初始化视图时出错',
    errorLoadingItems: '加载条目时出错',
    errorProcessingList: '处理列表时出错，请查看控制台。',
    promptSearchGame: '输入游戏名称',
    promptSearchAnime: '输入动漫名称',
    promptSearchMovie: '输入电影名称',
    promptSearchSeries: '输入剧集名称',
    promptSearchBook: '输入书名',
    promptSearchManga: '输入漫画名称',
    promptSearchPlaceholder: '输入名称…',
    promptSelectResult: '选择一个条目',
    promptIncludeDlc: 'DLC',
    promptSearchAction: '搜索',
    promptAddSelected: '添加',
    promptSelectedLabel: '已选择',
    promptReviewSelected: '检查所选条目',
    promptReviewSelectedSubtitle: '为保护数据源访问，条目会逐个导入。较大的批次可能需要一些时间。',
    promptConfirmSelected: '确认',
    promptRemoveSelected: '移除',
    promptPage: '页',
    promptPreviousPage: '上一页',
    promptNextPage: '下一页',
    promptAddModeTitle: '添加条目',
    promptAddModeProvider: '通过数据源查找',
    promptAddModeManual: '手动创建',
    promptAddModeProviderDesc: '搜索已配置的集成，并根据数据源信息创建条目。',
    promptAddModeManualDesc: '使用自己的字段创建一张空白卡片。',
    manualCreateTitle: '手动创建',
    manualCreateAction: '创建',
    manualMediaType: '媒体类型',
    manualTitleRequired: '名称不能为空。',
    manualSectionMain: '基本信息',
    manualSectionProgress: '进度',
    manualSectionExtra: '其他信息',
    manualCoverTitle: '封面',
    manualCoverUrl: '封面网址',
    manualCoverChoose: '选择文件',
    manualCoverClear: '清除',
    promptAddAnotherTitle: '继续添加？',
    promptAddAnotherBodyGame: '是否搜索并添加另一个游戏？',
    promptAddAnotherBodyAnime: '是否搜索并添加另一部动漫？',
    promptAddAnotherYes: '继续添加',
    promptAddAnotherNo: '完成',
    noticeNoResults: '未找到结果。',
    noticeMissingApiKey: '所选数据源缺少 API 密钥。',
    noticeProviderDisabled: '所选数据源已在设置中关闭。',
    noticeIntegrationsDisabled: '集成已在设置中关闭。',
    noticeCreated: '笔记已创建。',
    noticeSkipped: '已跳过。',
    noticeProviderTestSuccess: '数据源测试成功。',
    noticeProviderTestFail: '数据源测试失败。',
    noticeIntegrationsError: '集成错误',
    noticeSourceUpdated: '已关联数据源并更新元数据',
    noticeSourceNoChanges: '已关联数据源；没有可填充的空白元数据字段',
    noticeSourceFailed: '无法更新元数据来源',
    promptRateLimitTitle: '数据源请求已暂停',
    promptRateLimitBody: '为避免数据源延长封锁，剩余条目没有继续发出请求。请等待提示的冷却时间结束后再试。',
    promptFileExistsTitle: '卡片已存在',
    promptFileExistsBody: '你可以更新现有笔记、另建一张卡片，或保持现状。',
    promptFileExistsUpdate: '更新',
    promptFileExistsSeparate: '创建副本',
    promptFileExistsSkip: '保持现状',
    commonOk: '确定',
    commonRetry: '重试',
    commonCancel: '取消',
    commonBack: '返回',
    commonNoData: '暂无数据',
};
